# https://graphql-code-generator.com/
# https://github.com/piglovesyou/graphql-let#experimental-feature-resolver-types
# https://the-guild.dev/blog/better-type-safety-for-resolvers-with-graphql-codegen
# https://graphql-code-generator.com/docs/plugins/typescript-resolvers#use-your-model-types-mappers

schema: 'src/**/*.graphqls'
schemaEntrypoint: 'src/server/type-defs.graphqls'
documents: 'src/**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  # - typescript-resolvers TODO: not sure why this isn't working--see links above
config:
  contextType: .server/context.models#ContextModel
  mappers:
    # Show: ./server/shows/shows.models#ShowModel
    # Cast: ./server/shows/shows.models#CastModel
cacheDir: __generated__
